name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
   sdk: '>=3.3.3 <4.0.0'

dependencies:
   flutter:
      sdk: flutter
   cupertino_icons: ^1.0.6
   google_fonts: ^6.2.1
   http: ^1.2.2
   flutter_lints: ^3.0.0
   flutter_svg: ^2.0.10+1
   file_picker: ^5.0.0

flutter:
   uses-material-design: true
   assets:
      - assets/vectors/rectangle_13_x2.svg
      - assets/vectors/rectangle_41_x2.svg
      - assets/vectors/rectangle_11_x2.svg
      - assets/vectors/vector_31_x2.svg
      - assets/vectors/vector_42_x2.svg
      - assets/vectors/vector_27_x2.svg
      - assets/vectors/vector_7_x2.svg
      - assets/vectors/vector_3_x2.svg
      - assets/vectors/ellipse_1_x2.svg
      - assets/vectors/rectangle_3_x2.svg
      - assets/vectors/ellipse_2_x2.svg
      - assets/vectors/rectangle_5_x2.svg
      - assets/vectors/text_0_x2.svg
      - assets/vectors/vector_2_x2.svg
      - assets/vectors/vector_74_x2.svg
      - assets/vectors/vector_49_x2.svg
      - assets/vectors/text_1_x2.svg
      - assets/vectors/vector_57_x2.svg
      - assets/vectors/vector_11_x2.svg
      - assets/vectors/vector_15_x2.svg
      - assets/vectors/vector_33_x2.svg
      - assets/vectors/vector_47_x2.svg
      - assets/vectors/vector_19_x2.svg
      - assets/vectors/rectangle_12_x2.svg
      - assets/vectors/vector_64_x2.svg
      - assets/vectors/vector_69_x2.svg
      - assets/vectors/container_x2.svg
      - assets/vectors/rectangle_29_x2.svg
      - assets/vectors/vector_59_x2.svg
      - assets/vectors/vector_48_x2.svg
      - assets/vectors/rectangle_23_x2.svg
      - assets/vectors/rectangle_19_x2.svg
      - assets/vectors/vector_38_x2.svg
      - assets/vectors/rectangle_21_x2.svg
      - assets/vectors/vector_39_x2.svg
      - assets/vectors/rectangle_24_x2.svg
      - assets/vectors/vector_56_x2.svg
      - assets/vectors/vector_20_x2.svg
      - assets/vectors/vector_28_x2.svg
      - assets/vectors/rectangle_72_x2.svg
      - assets/images/rectangle_7.jpeg
      - assets/images/rectangle_15.png
      - assets/images/ellipse_3.jpeg
      - assets/images/basemap_image.png
      - assets/vectors/vector_29_x2.svg
      - assets/vectors/vector_21_x2.svg
      - assets/vectors/vector_10_x2.svg
      - assets/vectors/vector_24_x2.svg
      - assets/vectors/vector_54_x2.svg
      - assets/vectors/vector_63_x2.svg
      - assets/vectors/vector_66_x2.svg
      - assets/vectors/vector_34_x2.svg
      - assets/vectors/vector_58_x2.svg
      - assets/vectors/vector_52_x2.svg
      - assets/vectors/vector_36_x2.svg
      - assets/vectors/vector_61_x2.svg
      - assets/vectors/container_1_x2.svg
      - assets/images/rectangle_13.jpeg
      - assets/images/rectangle_16.jpeg
      - assets/images/rectangle_7.jpeg
      - assets/images/ellipse_3.jpeg
      - assets/images/rectangle_9.jpeg
      - assets/vectors/vector_40_x2.svg
      - assets/vectors/vector_16_x2.svg
      - assets/vectors/vector_26_x2.svg
      - assets/vectors/rectangle_161_x2.svg
      - assets/vectors/rectangle_71_x2.svg
      - assets/vectors/vector_18_x2.svg
      - assets/vectors/vector_62_x2.svg
      - assets/vectors/vector_5_x2.svg
      - assets/vectors/rectangle_91_x2.svg
      - assets/vectors/vector_73_x2.svg
      - assets/vectors/vector_65_x2.svg
      - assets/vectors/vector_72_x2.svg
      - assets/vectors/vector_23_x2.svg
      - assets/vectors/vector_30_x2.svg
      - assets/vectors/ellipse_12_x2.svg
      - assets/vectors/vector_32_x2.svg
      - assets/vectors/vector_9_x2.svg
      - assets/vectors/vector_51_x2.svg
      - assets/vectors/vector_41_x2.svg
      - assets/vectors/vector_1_x2.svg
      - assets/vectors/vector_46_x2.svg
      - assets/vectors/vector_55_x2.svg
      - assets/vectors/vector_45_x2.svg
      - assets/vectors/vector_25_x2.svg
      - assets/vectors/vector_50_x2.svg
      - assets/vectors/vector_12_x2.svg
      - assets/vectors/vector_43_x2.svg
      - assets/vectors/vector_60_x2.svg
      - assets/vectors/ellipse_22_x2.svg
      - assets/vectors/vector_70_x2.svg
      - assets/vectors/vector_14_x2.svg
      - assets/vectors/vector_68_x2.svg
      - assets/vectors/vector_6_x2.svg
      - assets/vectors/vector_71_x2.svg
      - assets/vectors/rectangle_131_x2.svg
      - assets/vectors/vector_8_x2.svg
      - assets/vectors/vector_13_x2.svg
      - assets/vectors/vector_x2.svg
      - assets/vectors/ellipse_11_x2.svg
      - assets/vectors/ellipse_21_x2.svg
      - assets/vectors/rectangle_31_x2.svg
      - assets/vectors/vector_37_x2.svg
      - assets/vectors/vector_67_x2.svg
      - assets/vectors/rectangle_1_x2.svg
      - assets/vectors/vector_4_x2.svg
      - assets/vectors/vector_22_x2.svg
      - assets/vectors/undraw_online_chat_re_c_4_lx_1_x2.svg
      - assets/vectors/vector_44_x2.svg
      - assets/vectors/rectangle_4_x2.svg